# permissions for end users to view rdbdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rdbdatabase-viewer-role
rules:
- apiGroups:
  - rdb.scaleway.com
  resources:
  - rdbdatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rdb.scaleway.com
  resources:
  - rdbdatabases/status
  verbs:
  - get
