# permissions for end users to edit rdbdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rdbdatabase-editor-role
rules:
- apiGroups:
  - rdb.scaleway.com
  resources:
  - rdbdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rdb.scaleway.com
  resources:
  - rdbdatabases/status
  verbs:
  - get
