# permissions for end users to view rdbinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rdbinstance-viewer-role
rules:
- apiGroups:
  - rdb.scaleway.com
  resources:
  - rdbinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rdb.scaleway.com
  resources:
  - rdbinstances/status
  verbs:
  - get
