# permissions for end users to view rdbusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rdbuser-viewer-role
rules:
- apiGroups:
  - rdb.scaleway.com
  resources:
  - rdbusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rdb.scaleway.com
  resources:
  - rdbusers/status
  verbs:
  - get
