# permissions for end users to edit rdbusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rdbuser-editor-role
rules:
- apiGroups:
  - rdb.scaleway.com
  resources:
  - rdbusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rdb.scaleway.com
  resources:
  - rdbusers/status
  verbs:
  - get
