apiVersion: v1
stringData:
  SCW_ACCESS_KEY: <YOUR-ACCESS-KEY>
  SCW_SECRET_KEY: <YOUR-SECRET-KEY>
  SCW_DEFAULT_PROJECT_ID: <YOUR-PROJECT-ID>
  SCW_DEFAULT_REGION: <YOUR-DEFAULT-REGION>
kind: Secret
metadata:
  name: scaleway-operator-secrets
  namespace: scaleway-operator-system
type: Opaque
